In [1]:
import numpy as np

# =========================================================
# 1. GRAYSCALE IMAGE
# =========================================================

image = np.array([
    [0,   50,  100, 150, 200],
    [50,  100, 150, 200, 255],
    [100, 150, 200, 255, 200],
    [150, 200, 255, 200, 150],
    [200, 255, 200, 150, 100]
], dtype=float)

print("Grayscale Image:")
print(image)


# =========================================================
# 2. KERNEL W1
# =========================================================

W1 = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
], dtype=float)

b1 = 0.0


# =========================================================
# 3. FORWARD PASS
# =========================================================

# Z1 = Convolution
Z1 = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        region = image[i:i+3, j:j+3]
        Z1[i, j] = np.sum(region * W1) + b1

print("\nZ1 - Convolution Output:")
print(Z1)


# A1 = ReLU(Z1)
A1 = np.maximum(0, Z1)

print("\nA1 - ReLU Output:")
print(A1)


# P1 = Max Pooling
P1 = np.zeros((2, 2))

for i in range(2):
    for j in range(2):
        region = A1[i:i+2, j:j+2]
        P1[i, j] = np.max(region)

print("\nP1 - Max Pooling Output:")
print(P1)


# S = Flatten
S = P1.flatten()

print("\nS - Flattened Output:")
print(S)


# =========================================================
# 4. FULLY CONNECTED LAYER
# =========================================================

W2 = np.array([0.5, 0.5, 0.5, 0.5])
b2 = 0.0

# Z2 = W2*S + b2
Z2 = np.dot(W2, S) + b2

print("\nZ2 - Fully Connected Output:")
print(Z2)


# A2 = Sigmoid(Z2)
A2 = 1 / (1 + np.exp(-Z2))

print("\nA2 - Sigmoid Output:")
print(A2)


# =========================================================
# 5. LOSS
# =========================================================

y = 1.0

# Loss = 1/2 (A2-y)^2
loss = 0.5 * (A2 - y) ** 2

print("\nLoss:")
print(loss)


# =========================================================
# 6. BACKWARD PASS
# =========================================================

learning_rate = 0.01

# ---------------------------------------------------------
# Gradient of W2
# ---------------------------------------------------------

dL_dW2 = (A2 - y) * A2 * (1 - A2) * S

print("\nGradient of W2:")
print(dL_dW2)


# ---------------------------------------------------------
# Numerical Gradient of W1
# ---------------------------------------------------------

epsilon = 0.0001
dL_dW1 = np.zeros_like(W1)

for i in range(3):
    for j in range(3):

        # W1 + epsilon
        W1_plus = W1.copy()
        W1_plus[i, j] += epsilon

        Z_plus = np.zeros((3, 3))

        for m in range(3):
            for n in range(3):
                region = image[m:m+3, n:n+3]
                Z_plus[m, n] = np.sum(region * W1_plus) + b1

        A_plus = np.maximum(0, Z_plus)

        P_plus = np.zeros((2, 2))

        for m in range(2):
            for n in range(2):
                region = A_plus[m:m+2, n:n+2]
                P_plus[m, n] = np.max(region)

        S_plus = P_plus.flatten()

        Z2_plus = np.dot(W2, S_plus) + b2
        A2_plus = 1 / (1 + np.exp(-Z2_plus))
        loss_plus = 0.5 * (A2_plus - y) ** 2


        # W1 - epsilon
        W1_minus = W1.copy()
        W1_minus[i, j] -= epsilon

        Z_minus = np.zeros((3, 3))

        for m in range(3):
            for n in range(3):
                region = image[m:m+3, n:n+3]
                Z_minus[m, n] = np.sum(region * W1_minus) + b1

        A_minus = np.maximum(0, Z_minus)

        P_minus = np.zeros((2, 2))

        for m in range(2):
            for n in range(2):
                region = A_minus[m:m+2, n:n+2]
                P_minus[m, n] = np.max(region)

        S_minus = P_minus.flatten()

        Z2_minus = np.dot(W2, S_minus) + b2
        A2_minus = 1 / (1 + np.exp(-Z2_minus))
        loss_minus = 0.5 * (A2_minus - y) ** 2


        # Numerical gradient
        dL_dW1[i, j] = (
            loss_plus - loss_minus
        ) / (2 * epsilon)


print("\nGradient of W1:")
print(dL_dW1)


# =========================================================
# 7. GRADIENT DESCENT UPDATE
# =========================================================

W1_new = W1 - learning_rate * dL_dW1

W2_new = W2 - learning_rate * dL_dW2


# =========================================================
# 8. FINAL RESULTS
# =========================================================

print("\nUpdated W1:")
print(W1_new)

print("\nUpdated W2:")
print(W2_new)

print("\nFinal Output:")
print(A2)

print("\nFinal Loss:")
print(loss)

print("\nCNN Forward and Backward Pass Completed Successfully.")

Grayscale Image:
[[  0.  50. 100. 150. 200.]
 [ 50. 100. 150. 200. 255.]
 [100. 150. 200. 255. 200.]
 [150. 200. 255. 200. 150.]
 [200. 255. 200. 150. 100.]]

Z1 - Convolution Output:
[[-300. -305. -205.]
 [-305. -205.    0.]
 [-205.    0.  205.]]

A1 - ReLU Output:
[[  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0. 205.]]

P1 - Max Pooling Output:
[[  0.   0.]
 [  0. 205.]]

S - Flattened Output:
[  0.   0.   0. 205.]

Z2 - Fully Connected Output:
102.5

A2 - Sigmoid Output:
1.0

Loss:
0.0

Gradient of W2:
[0. 0. 0. 0.]

Gradient of W1:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Updated W1:
[[ 1.  0. -1.]
 [ 1.  0. -1.]
 [ 1.  0. -1.]]

Updated W2:
[0.5 0.5 0.5 0.5]

Final Output:
1.0

Final Loss:
0.0

CNN Forward and Backward Pass Completed Successfully.
