In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load Iris dataset
iris = load_iris()

X = iris.data
y = iris.target

# Normalize data
X = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

# Convert target into one-hot encoding
Y = np.zeros((len(y), 3))
Y[np.arange(len(y)), y] = 1

# Split data
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

# Initialize weights and biases
np.random.seed(42)

w1 = np.random.rand(4, 5)
b1 = np.zeros(5)

w2 = np.random.rand(5, 3)
b2 = np.zeros(3)

# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Derivative of sigmoid
def derivative_sigmoid(a):
    return a * (1 - a)

# Training settings
epochs = 5000
lr = 0.1

# Backpropagation
for epoch in range(epochs):

    for i in range(len(X_train)):

        x = X_train[i]
        target = Y_train[i]

        # Forward propagation
        h1 = (x @ w1) + b1
        a1 = sigmoid(h1)

        h2 = (a1 @ w2) + b2
        a2 = sigmoid(h2)

        # Calculate error
        loss = np.mean((target - a2) ** 2)

        # Backward propagation
        o2 = (a2 - target) * derivative_sigmoid(a2)
        o1 = derivative_sigmoid(a1) * (w2 @ o2)

        # Update weights and biases
        w2 -= lr * np.outer(a1, o2)
        b2 -= lr * o2

        w1 -= lr * np.outer(x, o1)
        b1 -= lr * o1

# Testing
correct = 0
predictions = []

for i in range(len(X_test)):

    x = X_test[i]

    # Forward propagation
    h1 = (x @ w1) + b1
    a1 = sigmoid(h1)

    h2 = (a1 @ w2) + b2
    a2 = sigmoid(h2)

    # Predicted class
    prediction = np.argmax(a2)
    predictions.append(prediction)

    actual = np.argmax(Y_test[i])

    if prediction == actual:
        correct += 1

# Accuracy
accuracy = correct / len(X_test) * 100

print("Actual Classes:")
print(np.argmax(Y_test, axis=1))

print("\nPredicted Classes:")
print(predictions)

print("\nAccuracy:", accuracy, "%")

# Final weights and biases
print("\nFinal W1:")
print(w1)

print("\nFinal B1:")
print(b1)

print("\nFinal W2:")
print(w2)

print("\nFinal B2:")
print(b2)

Actual Classes:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]

Predicted Classes:
[np.int64(1), np.int64(0), np.int64(2), np.int64(1), np.int64(1), np.int64(0), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(0), np.int64(2), np.int64(0), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(0), np.int64(0)]

Accuracy: 100.0 %

Final W1:
[[ 1.45355159  3.37355047 -1.88943505 -0.26573913 -1.34942989]
 [ 2.31199875 -4.24985332 -4.58975509  1.21789808 -3.32280697]
 [-6.54998577  7.11686189 10.87726042  0.44888194  8.00930684]
 [-4.35730762  6.46678957  9.02956391  0.57013695  6.75704259]]

Final B1:
[  4.71803402  -2.72042968 -10.93483191   0.79781225  -8.26877072]

Final W2:
[[  5.05221399   0.21350937  -8.80837697]
 [ -8.48434686  12.66949815   1.88837834]
 [ -2.48579909 -10.33145824   7.06249713]
 [ -0.7295338